# Generated by Django 5.1.4 on 2025-01-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package'),
        ),
    ]
