# Generated by Django 5.1.4 on 2025-01-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_paymobpayment'),
        ('packages', '0003_alter_review_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_bookings', to='bookings.booking'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
