# Generated by Django 5.1.6 on 2025-03-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_price'),
        ('destinations', '0003_make_category_required'),
    ]

    operations = [
    ]
