# Generated by Django 5.1.6 on 2025-03-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_merge_20250308_0233'),
    ]

    operations = [
    ]
