# Generated by Django 5.1.6 on 2025-03-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_auto_20250308_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='السعر الأساسي للوجهة', max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.category'),
        ),
    ]
