# Generated by Django 5.1.6 on 2025-03-08 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destination_price_alter_destination_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='destinations.category'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
