# Generated by Django 5.1.4 on 2025-01-06 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_requests', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('bank', 'تحويل بنكي'), ('cash', 'نقدي'), ('card', 'بطاقة ائتمان')], default='cash', max_length=20)),
                ('start_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('account_holder', models.CharField(max_length=100, verbose_name='اسم صاحب الحساب')),
                ('transaction_date', models.DateField(verbose_name='تاريخ التحويل')),
                ('transaction_number', models.CharField(max_length=100, verbose_name='رقم التحويل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المحول')),
                ('receipt_image', models.ImageField(upload_to='bank_receipts/', verbose_name='صورة الإيصال')),
                ('payment_status', models.CharField(choices=[('pending', 'في انتظار التحويل'), ('completed', 'تم التحويل'), ('failed', 'فشل التحويل')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment', to='bookings.booking')),
            ],
        ),
    ]
