# Generated by Django 5.1.4 on 2025-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinganalysis',
            name='active_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinganalysis',
            name='average_booking_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookinganalysis',
            name='bookings_by_month',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bookinganalysis',
            name='cancelled_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinganalysis',
            name='most_popular_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='browser_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='page_visited',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
